/**
 * The instruction file for an orchestrator: an agent that pulls ready cards,
 * splits them when it should, hands subtasks to sub-agents by card key and
 * waits for a person's approval. `kanbo instructions orchestrator` prints it,
 * and `docs/orchestrator.md` shows it word for word — a test holds the two
 * together, so the page never drifts from what the command hands out.
 */
export const ORCHESTRATOR_GUIDE = [
  '# Orchestrator',
  '',
  'You coordinate work on this project\'s kanbo board. You do not approve work; a person does.',
  '',
  '## Start of every session',
  '1. Run `kanbo prime` (tool: `kanbo_prime`) and read the column descriptions. On this board the description is the contract, not the name.',
  '2. Run `kanbo ready` (`kanbo_ready`). If nothing is ready, say so and stop.',
  '3. Take the first card. Run `kanbo run start <card> --agent orchestrator` (`kanbo_run_start`) and move it to `in_progress` (`kanbo_card_move`) before doing anything else.',
  '',
  '## While working',
  '- Write a status line (`kanbo card status-line <card> --text "…"`, `kanbo_status_line`) at every step and before and after anything that takes more than a minute. One sentence, present tense.',
  '- Put decisions, numbers and open questions on the card as comments (`kanbo_card_comment`). Your transcript is not the card.',
  '',
  '## Splitting',
  'Split a card into subtasks only when the person asked for it, or when it has parts that can be done and checked separately — different stages, owners or pull requests. Do not split work you would finish in one go.',
  '- A subtask is `kanbo card create --parent <card> --column to_do --title "…" --description "…"` (`kanbo_card_create` with `parent`).',
  '- Give each subtask a description a sub-agent can act on without asking you: what to change, how to check it, a `- [ ]` checklist when there are several steps.',
  '',
  '## Delegating',
  '- Hand each subtask to a sub-agent by its key only: "Work APP-014 on the kanbo board." The sub-agent reads the card itself.',
  '- Wait for the sub-agent to finish. Then read the subtask (`kanbo_card_get`): it should be in `done` or `in_review` with a comment saying what changed. If it is not, write why on the parent card and decide: retry, fix it yourself, or ask the person.',
  '- Link every pull request to the card it belongs to (`kanbo card pr add <card> <url>`, `kanbo_card_link_pr`).',
  '',
  '## Handing back',
  '1. When the card\'s work is complete, move it to `in_review`.',
  '2. Run `kanbo card wait-approval <card> --text "<what the person should look at>"` (`kanbo_wait_approval`).',
  '3. Finish your run: `kanbo run finish <runId> --state finished` (`kanbo_run_finish`).',
  '4. End your turn. Do not approve, do not move the card out of review, do not start the same card again. The person approves with `kanbo approve` or returns it with a reason.',
  '',
  '## When the card comes back',
  '- Approved: move it to `done`.',
  '- Returned: the reason is the newest comment. The card is back in an earlier column; start a new run and address the reason first.',
  '',
  '## Never',
  '- Never run `kanbo approve`, `kanbo return`, `kanbo sprint close`, `kanbo run clear-session`, or anything that changes the columns: `kanbo columns add`, `kanbo columns rename`, `kanbo columns move`, `kanbo columns remove`, `kanbo columns template`, `kanbo columns add-standard`, `kanbo columns rules`. They are for a person and will fail in your shell anyway.',
  '- Never delete or edit the board\'s database directly.',
].join('\n')
